import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Calendar, Eye, EyeOff, Loader2, ArrowLeft } from 'lucide-react';
import { BLOG_POSTS } from '../data/mockData'; // 👇 Import thêm Mock Data để xem bài cũ

// Định nghĩa kiểu dữ liệu
interface BlogPost {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  image: string;
  date: string;
  readTime: string;
  content: {
    intro: string;
    keyPoints: string[];
    sections: { heading: string; body: string }[]; // Cấu trúc UI cần
    takeaways: string;
  };
  author?: { name: string };
}

const PostDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>(); 
  const [post, setPost] = useState<BlogPost | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  
  const [deepDiveMode, setDeepDiveMode] = useState(false);
  const [readingProgress, setReadingProgress] = useState(0);

  useEffect(() => {
    const fetchPostDetail = async () => {
      setIsLoading(true);
      
      if (!id) return;

      // 👇 LOGIC QUAN TRỌNG: Kiểm tra xem đây là bài Real (DB) hay Mock (Mẫu)
      const isRealPost = id.startsWith('real-');

      if (isRealPost) {
        // --- TRƯỜNG HỢP 1: BÀI VIẾT TỪ DATABASE ---
        try {
          // 1. Cắt bỏ chữ "real-" để lấy ID gốc (VD: "real-15" -> "15")
          const dbId = id.replace('real-', '');
          
          console.log(`📡 Đang lấy bài từ Server với ID gốc: ${dbId}`);
          
          // Gọi API (Dùng api/posts là đủ, hoặc tạo api get detail riêng)
          // Ở đây mình dùng cách đơn giản là lấy list rồi tìm, tối ưu hơn là gọi api/posts/:id
          const response = await fetch('http://localhost:4000/api/posts'); 
          const data = await response.json();
          
          const foundPostDB = data.find((p: any) => p.id.toString() === dbId);

          if (foundPostDB) {
            // 2. Chuyển đổi dữ liệu phẳng từ DB sang cấu trúc phân tầng của UI
            setPost({
              id: id, // Giữ nguyên ID trên URL
              title: foundPostDB.title,
              subtitle: "Deep dive into strategy mechanics",
              category: foundPostDB.category || "Strategy",
              image: foundPostDB.image || "https://source.unsplash.com/random",
              date: new Date(foundPostDB.createdAt).toLocaleDateString(),
              readTime: "5 min read",
              author: { name: "Tri Bui" }, // Hoặc lấy từ foundPostDB.authorId
              content: {
                // Intro lấy đoạn đầu
                intro: foundPostDB.content ? foundPostDB.content.substring(0, 200) + "..." : "",
                keyPoints: ["AI Generated Analysis", "Strategic Overview"],
                // 👇 QUAN TRỌNG: Nhét toàn bộ nội dung vào 1 section để hiển thị đầy đủ
                sections: [
                  { 
                    heading: "Full Analysis", 
                    body: foundPostDB.content // Hiển thị toàn bộ nội dung Markdown
                  }
                ],
                takeaways: "This content is generated by AI Agent."
              }
            });
          }
        } catch (error) {
          console.error("❌ Lỗi API:", error);
        }
      } else {
        // --- TRƯỜNG HỢP 2: BÀI VIẾT MẪU (MOCK DATA) ---
        console.log("📂 Đang tìm trong Mock Data...");
        const foundMock = BLOG_POSTS.find(p => p.id === id);
        if (foundMock) {
            // Ép kiểu về interface BlogPost của component này (nếu lệch type)
            // Ở đây mình giả sử cấu trúc Mock Data đã khớp
            setPost(foundMock as unknown as BlogPost);
        }
      }

      setIsLoading(false);
    };

    fetchPostDetail();
  }, [id]);

  // Logic Scroll Progress
  useEffect(() => {
    const handleScroll = () => {
      const total = document.documentElement.scrollTop;
      const windowHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
      setReadingProgress(total / windowHeight);
    }
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  if (isLoading) return <div className="min-h-screen flex justify-center items-center"><Loader2 className="animate-spin"/></div>;

  if (!post) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center dark:text-white">
        <h2 className="text-2xl font-bold mb-4">404 - Post Not Found</h2>
        <p className="mb-4 text-slate-500">Không tìm thấy bài viết có ID: {id}</p>
        <Link to="/" className="text-blue-500 hover:underline flex items-center">
          <ArrowLeft size={20} className="mr-2"/> Quay lại Trang chủ
        </Link>
      </div>
    );
  }

  return (
    <div className={`transition-colors duration-700 ease-in-out ${deepDiveMode ? 'bg-zinc-950 text-slate-300' : 'bg-white dark:bg-black text-slate-800 dark:text-slate-200'}`}>
      <div className="fixed top-0 left-0 h-1 bg-black dark:bg-white z-[60] w-full origin-left transform" style={{ transform: `scaleX(${readingProgress})` }}></div>
      
      <div className="fixed right-8 top-1/2 -translate-y-1/2 z-40 hidden xl:flex flex-col space-y-4">
        <button onClick={() => setDeepDiveMode(!deepDiveMode)} className={`p-3 rounded-full shadow-lg transition-all ${deepDiveMode ? 'bg-white text-black' : 'bg-black text-white'}`}>
            {deepDiveMode ? <EyeOff size={20} /> : <Eye size={20} />}
        </button>
      </div>

      {!deepDiveMode && (
        <div className="relative h-[60vh]">
            <img src={post.image} alt={post.title} className="w-full h-full object-cover filter brightness-50"/>
            <div className="absolute inset-0 flex items-center justify-center text-center p-4">
                <div className="max-w-4xl text-white">
                    <span className="border border-white/50 px-4 py-1 text-xs font-bold uppercase tracking-widest mb-6 inline-block">{post.category}</span>
                    <h1 className="text-4xl md:text-6xl font-serif font-bold mb-6">{post.title}</h1>
                    <div className="flex justify-center gap-6 text-sm font-bold uppercase tracking-widest opacity-80">
                        <span className="flex items-center"><Calendar size={14} className="mr-2"/> {post.date}</span>
                        {post.author && <span>By {post.author.name}</span>}
                    </div>
                </div>
            </div>
        </div>
      )}

      <div className={`max-w-3xl mx-auto px-4 py-20 relative`}>
        {/* Intro Section */}
        {post.content.intro && (
            <p className="text-2xl font-serif leading-relaxed mb-12 italic opacity-80">
                "{post.content.intro}"
            </p>
        )}
        
        {/* Main Content Render */}
        <div className="prose prose-lg dark:prose-invert max-w-none">
            {post.content.sections.map((sec, idx) => (
                <div key={idx} className="mb-10">
                    {/* Chỉ hiện heading nếu không phải là Full Analysis (để đỡ lặp) */}
                    {sec.heading !== "Full Analysis" && <h3>{sec.heading}</h3>}
                    
                    {/* 👇 SỬ DỤNG white-space-pre-wrap ĐỂ GIỮ XUỐNG DÒNG CỦA AI */}
                    <div className="whitespace-pre-wrap font-sans text-lg leading-8">
                        {sec.body}
                    </div>
                </div>
            ))}
        </div>
      </div>
    </div>
  );
};

export default PostDetail;